export const bodyTypes = [
  "SUV",
  "Premium SUV",
  "Hatchback",
  "Premium Hatchback",
  "Sedan",
  "MUV",
  "Luxury",
];

export const carData = [
  {
    status: "featured",
    year: 2022,
    slug: "hyundai-creta-suv",
    categorytype: "SUV",
    km: 25000,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 1200000,
  },
  {
    status: "featured",
    year: 2022,
    slug: "hyundai-creta-suv 2",
    categorytype: "SUV",
    km: 25000,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 1200000,
  },
  {
    status: "featured",
    year: 2022,
    slug: "hyundai-creta-suv 3",
    categorytype: "SUV",
    km: 25000,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 1200000,
  },
  {
    status: "featured",
    year: 2022,
    slug: "hyundai-creta-suv 4",
    categorytype: "SUV",
    km: 25000,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 1200000,
  },
  {
    status: "featured",
    year: 2023,
    slug: "mg-hector-premium-suv",
    categorytype: "Premium SUV",
    km: 15000,
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 1800000,
  },
  {
    status: "trending",
    year: 2021,
    slug: "maruti-swift-hatchback",
    categorytype: "Hatchback",
    km: 30000,
    fuelType: "Petrol",
    transmission: "Manual",
    price: 650000,
  },
  {
    status: "featured",
    year: 2022,
    slug: "baleno-premium-hatchback",
    categorytype: "Premium Hatchback",
    km: 12000,
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 900000,
  },
  {
    status: "featured",
    year: 2020,
    slug: "honda-city-sedan",
    categorytype: "Sedan",
    km: 40000,
    fuelType: "Diesel",
    transmission: "Manual",
    price: 800000,
  },
  {
    status: "featured",
    year: 2019,
    slug: "innova-crysta-muv",
    categorytype: "MUV",
    km: 50000,
    fuelType: "Diesel",
    transmission: "Automatic",
    price: 1600000,
  },
  {
    status: "featured",
    year: 2021,
    slug: "bmw-5series-luxury",
    categorytype: "Luxury",
    km: 20000,
    fuelType: "Petrol",
    transmission: "Automatic",
    price: 4500000,
  },
];
